// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiqckbKb6SpvI5BjVJBaTco9C6VngSyXg',
    appId: '1:235430571802:web:2e20ce00edb1e8df5c06a3',
    messagingSenderId: '235430571802',
    projectId: 'swipejobnow-app',
    authDomain: 'swipejobnow-app.firebaseapp.com',
    storageBucket: 'swipejobnow-app.appspot.com',
    measurementId: 'G-JBZR90PFTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwkNGTivkj4olxU43TiHKLG7pd5W8fgdY',
    appId: '1:235430571802:android:271f58bef5843a1d5c06a3',
    messagingSenderId: '235430571802',
    projectId: 'swipejobnow-app',
    storageBucket: 'swipejobnow-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEbWsCLKQOVK0Lj230dZja6M5TIlx3esE',
    appId: '1:235430571802:ios:1ce8978ac6bc55b15c06a3',
    messagingSenderId: '235430571802',
    projectId: 'swipejobnow-app',
    storageBucket: 'swipejobnow-app.appspot.com',
    iosBundleId: 'com.example.finalyearproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEbWsCLKQOVK0Lj230dZja6M5TIlx3esE',
    appId: '1:235430571802:ios:1ce8978ac6bc55b15c06a3',
    messagingSenderId: '235430571802',
    projectId: 'swipejobnow-app',
    storageBucket: 'swipejobnow-app.appspot.com',
    iosBundleId: 'com.example.finalyearproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiqckbKb6SpvI5BjVJBaTco9C6VngSyXg',
    appId: '1:235430571802:web:acb66b0647a3fafa5c06a3',
    messagingSenderId: '235430571802',
    projectId: 'swipejobnow-app',
    authDomain: 'swipejobnow-app.firebaseapp.com',
    storageBucket: 'swipejobnow-app.appspot.com',
    measurementId: 'G-90WMFNG4YE',
  );
}
